spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/haconaka_backend
    username: ds6951
    password: 1596ibaJ
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
server:
  port: 8080
logging:
  level:
    com.haconaka.demo: INFO
    org.hibernate.SQL: WARN
youtube:
  callback-base-url: "https://cf94-2400-2410-b7e3-cf00-ed06-73d8-e3ce-73cf.ngrok-free.app"
  api-key: "AIzaSyDaJwlJQy--MSHz_DRBAcvTi2tc4Cg78CY"